### ISSUE TITLE
Почему CommandSender?

### ISSUE THREAD

**Issue by aquaminer** [AlexBrin/aEconomy#1]
Здраствуйте, почему вы используете CommandSender?
 https://github.com/AlexBrin/aEconomy/blob/master/src/AlexBrin/aEconomy.php#L117

Это видь лишает возможности использования простого $this->getServer()->getPlayer('nickname'); для использования как от имени перевода.

Если я не прав, поправьте пожалуйста

**Comment by AlexBrin** [comment]
CommandSender - это интерфейс
Player по умолчанию реализует этот интерфейс и это легко проверяется:
`var_dump($player instanceof \pocketmine\command\CommandSender)`
(https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L168)
